dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.5.3
  - 2.3.8
gemfile:
  - gemfiles/rails-5-2.gemfile
  - gemfiles/rails-master.gemfile
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rspec spec
jobs:
  exclude:
    - rvm: '2.3.8'
      gemfile: gemfiles/rails-master.gemfile
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
