dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/Gemfile.rails-5-2
  - gemfiles/Gemfile.rails-5-1
  - gemfiles/Gemfile.rails-5-0
  - gemfiles/Gemfile.rails-4-2
  - gemfiles/Gemfile.rails-master
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rspec spec
jobs:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-master
